# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeContext < Formula
  desc ""
  homepage "https://github.com/DB-Vincent/kube-context"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DB-Vincent/kube-context/releases/download/v0.2.1/kube-context_Darwin_arm64.tar.gz"
      sha256 "a61571ec993ba4bc20586bdd170a04fda08eeff065fe1622fbe61c4d71f0912f"

      def install
        bin.install "kube-context"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DB-Vincent/kube-context/releases/download/v0.2.1/kube-context_Darwin_x86_64.tar.gz"
      sha256 "6bf95f87e4d821cef281d03834284319d1c317ad1943ff2a85060e6fb60be447"

      def install
        bin.install "kube-context"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DB-Vincent/kube-context/releases/download/v0.2.1/kube-context_Linux_arm64.tar.gz"
      sha256 "95889a59c311d447c93babf4958e8bf68877ffce776744346ab66c4603a25853"

      def install
        bin.install "kube-context"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DB-Vincent/kube-context/releases/download/v0.2.1/kube-context_Linux_x86_64.tar.gz"
      sha256 "cad7cd991a1cdc9724eccafb062b58c90033b04d4abf975c89758d90c7c90988"

      def install
        bin.install "kube-context"
      end
    end
  end
end
