# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 24
Set Width 1200
Set Height 450

Type "kube-context"
Sleep 500ms
Enter

Sleep 750ms
Enter

Sleep 750ms
Type "kubectl cluster-info"
Sleep 500ms
Enter

Sleep 750ms
Type "kube-context"
Sleep 500ms
Enter

Sleep 250ms
Down
Sleep 500ms
Enter

Sleep 750ms
Type "kubectl cluster-info"
Sleep 500ms
Enter

# Admire the output for a bit.
Sleep 2s
