Output demo-default-namespace.gif

Set FontSize 24
Set Width 1400
Set Height 450

Sleep 1000ms
Type "kube-context set-default-namespace"
Sleep 500ms
Enter

Sleep 750ms
Down@200ms 4
Sleep 1000ms
Enter

Sleep 750ms
Type "kubectl get pods"
Sleep 500ms
Enter

Sleep 1000ms
Type "kube-context set-default-namespace"
Sleep 500ms
Enter

Sleep 750ms
Down@200ms 5
Sleep 1000ms
Enter

Sleep 750ms
Type "kubectl get pods"
Sleep 500ms
Enter

# Admire the output for a bit.
Sleep 2s
